name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.5'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Checkout source
      uses: actions/checkout@v2.3.4

    - name: Run unit tests
      run: pipenv run nosetests
